name: riverpod
description: Flutter project with RiverPod

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #provider: ^6.0.4
  #flutter_riverpod: ^1.0.0-dev.11
  #flutter_riverpod: ^2.1.1
  cupertino_icons: ^1.0.2
  #state_notifier: ^0.7.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

