name: analyzer_sm
description: "Analyzer package for project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  pedantic_mono: ^1.25.0
  dart_code_metrics: ^5.7.6
  #flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  #uses-material-design: true