name: firebase_project
description: Store Flutter project with Firebase.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.5
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  cupertino_icons: ^1.0.2
  model_sm:
    path: ./packages/model_sm
  business_sm:
    path: ./packages/business_sm

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  analyzer_sm:
    path: ./packages/analyzer_sm

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/

#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700
