name: firebase_project
description: Store Flutter project with Firebase.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: any
  fluro: ^2.0.5
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  get_it: ^7.3.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  model_sm:
    path: ./packages/model_sm
  business_sm:
    path: ./packages/business_sm

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  analyzer_sm:
    path: ./packages/analyzer_sm

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/
    - assets/images/ui/auth/auth_def.jpg

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/UbuntuCondensed-Regular.ttf
