name: model_sm
description: Model package for SM project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.3.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  analyzer_sm:
    path: ../analyzer_sm

flutter:
  uses-material-design: true
