name: module1_analyzer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  pedantic_mono: ^1.20.0
  dart_code_metrics: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0

flutter:
