name: business
description: Business Layer
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # TODO 1: include GetIt as a dependency
  get_it: ^7.3.0

  model:
    path: ../model
  data:
    path: ../data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
