name: skeleton_app
description: Example of clear structure Flutter app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  module1_business:
    path: ./packages/module1_business
  module1_model:
    path: ./packages/module1_model
  cupertino_icons: ^1.0.2
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  module1_analyzer:
    path: ./packages/module1_analyzer
  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
