name: nss
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.5

  cupertino_icons: ^1.0.8

flutter_native_splash:
  background_image: "assets/background.png"
  image: assets/splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

