// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVJGO_sy4sRraDUwcgOzoGeIBkpUWoIaY',
    appId: '1:1070261261652:web:d4ecc9552a72203c21a4c1',
    messagingSenderId: '1070261261652',
    projectId: 'study-firebase-216e3',
    authDomain: 'study-firebase-216e3.firebaseapp.com',
    databaseURL: 'https://study-firebase-216e3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-firebase-216e3.appspot.com',
    measurementId: 'G-JXD8SWBRKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnvmRcGvzGoKtb9bFIGtWyFQTFx1tcGGU',
    appId: '1:1070261261652:android:fc7a6e455c348c9e21a4c1',
    messagingSenderId: '1070261261652',
    projectId: 'study-firebase-216e3',
    databaseURL: 'https://study-firebase-216e3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-firebase-216e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVmCjHCFiRCBHC-ChBjfo9ONjtr7UPRLU',
    appId: '1:1070261261652:ios:52de77185e2e6add21a4c1',
    messagingSenderId: '1070261261652',
    projectId: 'study-firebase-216e3',
    databaseURL: 'https://study-firebase-216e3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-firebase-216e3.appspot.com',
    iosClientId: '1070261261652-8ejbchc0ptdltnav9dn7455g3ckv2s7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVmCjHCFiRCBHC-ChBjfo9ONjtr7UPRLU',
    appId: '1:1070261261652:ios:52de77185e2e6add21a4c1',
    messagingSenderId: '1070261261652',
    projectId: 'study-firebase-216e3',
    databaseURL: 'https://study-firebase-216e3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-firebase-216e3.appspot.com',
    iosClientId: '1070261261652-8ejbchc0ptdltnav9dn7455g3ckv2s7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );
}
