// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC085BQKH2hvSZJk7n8gWGR2EWifNJqb8A',
    appId: '1:753903868400:web:f1f9c020787a61f375a535',
    messagingSenderId: '753903868400',
    projectId: 'sk-firebase-shop',
    authDomain: 'sk-firebase-shop.firebaseapp.com',
    storageBucket: 'sk-firebase-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfyXQGi3G-j9BaNFCEE2VyxZBXTO-oZdQ',
    appId: '1:753903868400:android:5ba6dec50f81863375a535',
    messagingSenderId: '753903868400',
    projectId: 'sk-firebase-shop',
    storageBucket: 'sk-firebase-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRv2ZlMI9yb8qDK1gx-HkLiFZtkXTbAxM',
    appId: '1:753903868400:ios:5eddda3cdd4dd79a75a535',
    messagingSenderId: '753903868400',
    projectId: 'sk-firebase-shop',
    storageBucket: 'sk-firebase-shop.appspot.com',
    iosClientId: '753903868400-oaj828vsrc7svr0i8jgt5grkiav0pq8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFirebaseShop',
  );
}
