name: advanced_widgets
description: Homework Advanced Widgets

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.4
  flutter_bloc: ^8.1.1
  model_sm:
    path: ./packages/model_sm
  business_sm:
    path: ./packages/business_sm
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer_sm:
    path: ./packages/analyzer_sm

flutter:
  uses-material-design: true

  #assets:
  #  - assets/images/
  #  - images/a_dot_ham.jpeg

#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700

