name: business_sm
description: Package with Business Logic layer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  model_sm:
    path: ../model_sm
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer_sm:
    path: ../analyzer_sm

  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

